enabled = ["llama7b", "mistral7b", "phi2b"]

[models.llama7b]
ipaddr = "127.0.0.1"
port = 8000
host = "localhost"
count_tokens = true
search = "recursive-all" # will search all fields in json body with fieldName "content"
outheader = "content"
inheader = "content"
