enabled = ["llama7b"]

[models.llama7b]
ipaddr = "10.5.0.6"
port = 8000
host = "dummyai"
count_tokens = true
search = "recursive-all" # will search all fields in json body with fieldName "content"
outheader = "content"
inheader = "content"
